import React, { useCallback, useState } from 'react'
import { ActivityIndicator, Alert, FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from 'react-native'
import { useFocusEffect } from '@react-navigation/native'
import { colors, radius, spacing } from '@/src/theme'
import { apiService, handleApiError } from '@shared/services/api'

export default function CollaborationsScreen() {
  const [deals, setDeals] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<any | null>(null); const [documents, setDocuments] = useState<any[]>([]); const [name, setName] = useState(''); const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { try { const r = await apiService.getDeals(); setDeals(r?.deals || r?.collabs || r?.data || []) } catch (e) { handleApiError(e, 'Failed to load collaborations') } finally { setLoading(false) } }, [])
  useFocusEffect(useCallback(() => { load() }, [load]))
  const open = async (deal: any) => { setSelected(deal); try { const r = await apiService.getDocuments(deal.id); setDocuments(r?.documents || r?.data || []) } catch (e) { handleApiError(e, 'Failed to load documents') } }
  const sign = async (doc: any) => { if (!name.trim()) return Alert.alert('Name required', 'Enter your full legal name before signing.'); setBusy(true); try { await apiService.signDocument(doc.id, name.trim()); setName(''); if (selected) open(selected) } catch (e) { handleApiError(e, 'Failed to sign document') } finally { setBusy(false) } }
  if (loading) return <View style={styles.center}><ActivityIndicator color={colors.neon} /></View>
  if (selected) return <View style={styles.root}><FlatList contentContainerStyle={styles.list} data={documents} keyExtractor={(x) => String(x.id)} ListHeaderComponent={<><Pressable onPress={() => setSelected(null)}><Text style={styles.back}>Back to collaborations</Text></Pressable><Text style={styles.heading}>{selected.campaignTitle || selected.campaign?.title || 'Collaboration'}</Text><TextInput value={name} onChangeText={setName} placeholder="Full name for signing" placeholderTextColor={colors.textSubtle} style={styles.input} /></>} ListEmptyComponent={<Text style={styles.empty}>No documents have been generated yet.</Text>} renderItem={({ item }) => <View style={styles.card}><Text style={styles.title}>{item.kind || 'Agreement'}</Text><Text style={styles.meta}>{item.status || 'pending_signature'}</Text>{item.status === 'pending_signature' && <Pressable disabled={busy} onPress={() => sign(item)} style={styles.primary}><Text style={styles.primaryText}>{busy ? 'Signing...' : 'Review and sign'}</Text></Pressable>}</View>} /></View>
  return <View style={styles.root}><FlatList contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={false} onRefresh={load} tintColor={colors.neon} />} data={deals} keyExtractor={(x) => String(x.id)} ListEmptyComponent={<Text style={styles.empty}>Accepted collaborations will appear here.</Text>} renderItem={({ item }) => <Pressable onPress={() => open(item)} style={styles.card}><Text style={styles.title}>{item.campaignTitle || item.campaign?.title || 'Collaboration'}</Text><Text style={styles.meta}>{item.status || 'active'} · Tap to view documents and deliverables</Text></Pressable>} /></View>
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.bg }, center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.bg }, list: { padding: spacing.lg, gap: spacing.md, flexGrow: 1 }, back: { color: colors.blue, marginBottom: spacing.md }, heading: { color: colors.text, fontSize: 22, fontWeight: '800', marginBottom: spacing.md }, input: { backgroundColor: colors.card, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: spacing.md, color: colors.text }, card: { backgroundColor: colors.card, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: spacing.lg }, title: { color: colors.text, fontWeight: '700' }, meta: { color: colors.textMuted, marginTop: spacing.sm }, primary: { alignSelf: 'flex-start', backgroundColor: colors.neon, borderRadius: radius.pill, paddingHorizontal: spacing.lg, paddingVertical: spacing.sm, marginTop: spacing.md }, primaryText: { color: '#000', fontWeight: '800' }, empty: { color: colors.textMuted, textAlign: 'center', marginTop: spacing.xxxl } })
