import React, { useCallback, useState } from 'react'
import { ActivityIndicator, Alert, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native'
import { useFocusEffect } from '@react-navigation/native'
import { colors, radius, spacing } from '@/src/theme'
import { apiService, handleApiError } from '@shared/services/api'

export default function DealInvitesScreen() {
  const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [busy, setBusy] = useState<string | null>(null)
  const load = useCallback(async () => { try { const res = await apiService.getDealInvites({ status: 'pending' }); setItems(res?.invites || res?.data || []) } catch (e) { handleApiError(e, 'Failed to load invites') } finally { setLoading(false); setRefreshing(false) } }, [])
  useFocusEffect(useCallback(() => { load() }, [load]))
  const act = async (id: string) => { setBusy(id); try { await apiService.acceptDealInvite(id); setItems((x) => x.filter((i) => i.id !== id)) } catch (e) { handleApiError(e, 'Failed to accept invite') } finally { setBusy(null) } }
  if (loading) return <View style={styles.center}><ActivityIndicator color={colors.neon} /></View>
  return <View style={styles.root}><FlatList data={items} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); load() }} tintColor={colors.neon} />} contentContainerStyle={styles.list} keyExtractor={(i) => String(i.id)} ListEmptyComponent={<Empty text="No pending campaign invites" />} renderItem={({ item }) => <View style={styles.card}><Text style={styles.title}>{item.campaignTitle || item.campaign?.title || 'Campaign invitation'}</Text><Text style={styles.meta}>{item.message || 'A brand invited you to collaborate.'}</Text><View style={styles.actions}><Pressable disabled={!!busy} onPress={() => act(item.id)} style={styles.primary}><Text style={styles.primaryText}>{busy === item.id ? 'Saving...' : 'Accept'}</Text></Pressable></View></View>} /></View>
}
function Empty({ text }: { text: string }) { return <View style={styles.center}><Text style={styles.empty}>{text}</Text></View> }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.bg }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.bg }, list: { padding: spacing.lg, gap: spacing.md, flexGrow: 1 }, card: { backgroundColor: colors.card, borderColor: colors.border, borderWidth: 1, borderRadius: radius.lg, padding: spacing.lg }, title: { color: colors.text, fontSize: 16, fontWeight: '700' }, meta: { color: colors.textMuted, fontSize: 13, lineHeight: 19, marginTop: spacing.sm }, actions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.lg, justifyContent: 'flex-end' }, primary: { backgroundColor: colors.neon, borderRadius: radius.pill, paddingHorizontal: spacing.lg, paddingVertical: spacing.sm }, primaryText: { color: '#000', fontWeight: '800' }, secondary: { borderColor: colors.border, borderWidth: 1, borderRadius: radius.pill, paddingHorizontal: spacing.lg, paddingVertical: spacing.sm }, secondaryText: { color: colors.text, fontWeight: '700' }, empty: { color: colors.textMuted } })
