import React, { useCallback, useState } from 'react'
import { ActivityIndicator, Alert, FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from 'react-native'
import { useFocusEffect } from '@react-navigation/native'
import { colors, radius, spacing } from '@/src/theme'
import { apiService, handleApiError } from '@shared/services/api'

export default function SettlementsScreen() {
  const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [campaignId, setCampaignId] = useState(''); const [amount, setAmount] = useState(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false)
  const load = useCallback(async () => { try { const r = await apiService.getSettlements(); setItems(r?.settlementRequests || r?.data || []) } catch (e) { handleApiError(e, 'Failed to load settlements') } finally { setLoading(false) } }, [])
  useFocusEffect(useCallback(() => { load() }, [load]))
  const submit = async () => { if (!campaignId.trim()) return Alert.alert('Campaign required', 'Enter the campaign ID for the completed deal.'); setSaving(true); try { await apiService.createSettlement({ campaignId: campaignId.trim(), amount: amount.trim() ? Math.round(Number(amount) * 100) : undefined, message }); setCampaignId(''); setAmount(''); setMessage(''); Alert.alert('Submitted', 'Settlement request created.'); load() } catch (e) { handleApiError(e, 'Failed to create settlement') } finally { setSaving(false) } }
  if (loading) return <View style={styles.center}><ActivityIndicator color={colors.neon} /></View>
  return <FlatList style={styles.root} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={false} onRefresh={load} tintColor={colors.neon} />} ListHeaderComponent={<><Text style={styles.heading}>Request settlement</Text><Text style={styles.hint}>Use this for a completed collaboration while the brand reviews payment.</Text><TextInput value={campaignId} onChangeText={setCampaignId} placeholder="Campaign ID" placeholderTextColor={colors.textSubtle} style={styles.input} /><TextInput value={amount} onChangeText={setAmount} placeholder="Amount in ₹ (optional)" keyboardType="numeric" placeholderTextColor={colors.textSubtle} style={styles.input} /><TextInput value={message} onChangeText={setMessage} placeholder="Message (optional)" placeholderTextColor={colors.textSubtle} style={styles.input} /><Pressable onPress={submit} disabled={saving} style={styles.primary}><Text style={styles.primaryText}>{saving ? 'Submitting...' : 'Request settlement'}</Text></Pressable><Text style={styles.heading}>History</Text></>} data={items} keyExtractor={(x) => String(x.id)} ListEmptyComponent={<Text style={styles.empty}>No settlement requests yet.</Text>} renderItem={({ item }) => <View style={styles.card}><Text style={styles.title}>Campaign {String(item.campaign_id || item.campaignId || '').slice(-8)}</Text><Text style={styles.meta}>{item.status || 'pending'} · ₹{(Number(item.amount_minor || item.amount || 0) / 100).toLocaleString()}</Text></View>} />
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.bg }, center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.bg }, list: { padding: spacing.lg, gap: spacing.md, flexGrow: 1 }, heading: { color: colors.text, fontSize: 20, fontWeight: '800', marginTop: spacing.md }, hint: { color: colors.textMuted, lineHeight: 19 }, input: { backgroundColor: colors.card, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: spacing.md, color: colors.text }, primary: { alignItems: 'center', backgroundColor: colors.neon, borderRadius: radius.pill, padding: spacing.md }, primaryText: { color: '#000', fontWeight: '800' }, card: { backgroundColor: colors.card, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: spacing.md }, title: { color: colors.text, fontWeight: '700' }, meta: { color: colors.textMuted, marginTop: spacing.sm }, empty: { color: colors.textMuted, textAlign: 'center' } })
